version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-kroger}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:5432/${POSTGRES_DB:-kroger}
    ports:
      - "9000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE=http://backend:8000
    ports:
      - "9100:5173"
    # No bind mount to keep image-installed node_modules; hot reload still works inside container
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]
    depends_on:
      - backend

volumes:
  pg_data:

